// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5FZQI3DvFoJ0e04mrhsG2Z9gbvn8Rg74',
    appId: '1:962724192471:web:20aa143294fa26b814d092',
    messagingSenderId: '962724192471',
    projectId: 'hhmtestperf-18d27',
    authDomain: 'hhmtestperf-18d27.firebaseapp.com',
    storageBucket: 'hhmtestperf-18d27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnt1MLcV_21A00lYAs2-qbZhPb2HUFEBE',
    appId: '1:962724192471:android:35da6c73e16fbb6314d092',
    messagingSenderId: '962724192471',
    projectId: 'hhmtestperf-18d27',
    storageBucket: 'hhmtestperf-18d27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvT3i75t5ea8wl73hKoq5CDD_lqEi_YbE',
    appId: '1:962724192471:ios:1e3731ac0091585614d092',
    messagingSenderId: '962724192471',
    projectId: 'hhmtestperf-18d27',
    storageBucket: 'hhmtestperf-18d27.appspot.com',
    iosBundleId: 'com.example.perfAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvT3i75t5ea8wl73hKoq5CDD_lqEi_YbE',
    appId: '1:962724192471:ios:65c9cea0091760f814d092',
    messagingSenderId: '962724192471',
    projectId: 'hhmtestperf-18d27',
    storageBucket: 'hhmtestperf-18d27.appspot.com',
    iosBundleId: 'com.example.perfAndroid.RunnerTests',
  );
}
